name: Build SFML App

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SFML 2.6
        shell: bash
        run: |
          git clone --branch 2.6.x https://github.com/SFML/SFML.git
          cd SFML
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../../SFML-install -DBUILD_SHARED_LIBS=OFF
          cmake --build . --target install --config Release

      - name: Build project
        shell: bash
        run: |
          g++ -std=c++17 main.cpp SettingsState.cpp \
            -ISFML-install/include \
            -LSFML-install/lib \
            -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio \
            -o app.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: app.exe
