name: Build SFML App (Windows)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Забираем код
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Устанавливаем MSYS2 + SFML (САМЫЙ СТАБИЛЬНЫЙ СПОСОБ)
      - name: Setup MSYS2 and install SFML
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-sfml

      # 3. Сборка проекта
      - name: Build project
        shell: msys2 {0}
        run: |
          g++ -std=c++17 main.cpp MenuState.cpp GameState.cpp RulesState.cpp SettingsState.cpp ^
          -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio ^
          -o app.exe

      # 4. Загружаем exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gorodki-build
          path: app.exe
